### ISSUE TITLE
[Linux][patch]  build broken

### ISSUE THREAD

**Issue by ebachard** [AugustoRuiz/sdl2glsl#1]
Hi,

I found your proposal on libsdl.org forum. Ref: https://discourse.libsdl.org/t/sdl2-glsl-shader-working-example-using-sdl-renderer/22637

Thanks a lot for sharing your code !

The issue:  build broken on Linux (x86_64, kernel 4.4.0-53-generic) + instant crash (maybe my old graphic card)

The log : 
We compiled against SDL version 2.0.5 ...
And we are linking against SDL version 2.0.5.
Current OpenGL version : 3.0
Es OpenGL!
Erreur de segmentation  <<  bad :-/

On Linux, the build is broken, and I had to modify your code to compile the binary. This is just a try, and maybe my code is not that clean, anyway. I'll attach a patch. e.g. was the missing libGLEW linking, and some little things in the code. Nevertheless, it does not yet work: got a crash, probably due to my old graphical card, not able to compile the shaders you wrote. I'll continue to search.

BTW : what is the minimal expected OpenGL version to make it work ? Got 3.0 (should be 3.3, don't ask me what happened) on my machine, but this is probably not enough ?

Important: just rename the attached file and you'll have a simple git diff I did. Do what you want with the code, and use whatever license you want. 
[full_diff.diff.txt](https://github.com/AugustoRuiz/sdl2glsl/files/1075987/full_diff.diff.txt)

Last but not least (for lazy guys like me)  :  ln -s Makefile.linux Makefile

**Comment by AugustoRuiz** [comment]
Hi! Thanks for the feedback!

I have now a working version in OS X and Windows that doesn't need glew. I hope to have a Linux working version by the end of the week. :)

About the ln-s... What about OS X devs? I'd rather prefer lazy guys do the link themselves...

**Comment by AugustoRuiz** [comment]
Last commit fixed the issue for Linux too.

**Comment by ebachard** [comment]
I confirm, everything works fine with your last commit, and I'll be able to study (and why not understand) better the glsl you implemented. 

Thanks a lot !

To answer you about the makefile, the idea was simply to tell how to reduce the command line to a simple " make". Was just a suggestion nothing more. On my side, I often have to test on both OS's so I created a script like select_OS, containing: 

```
#!/bin/bash

echo -e "Choose your OS (enter Linux or MacOSX) \n"

read a_choice

if test "x$a_choice" = "xLinux"
  then
    rm -f Makefile
    ln -s Makefile.linux Makefile
fi

if test "x$a_choice" = "xMacOSX"
  then
    rm -f Makefile
    ln -s Makefile.OSX Makefile
fi

```

**Comment by AugustoRuiz** [comment]
I like the idea! Having a shell script for Linux/OSX... But probably there's a way of finding which one is it, instead of asking the user ;)

**Comment by ebachard** [comment]
Not sure this will help you, but for cross-compilation purpose, I'm myself using a uniq Makefile.

More precisely, I'm using:

    UNAME_S = $(shell uname -s)
   
    ifeq (${UNAME_S}, Linux)
         CURRENT_OS += Linux
         OS_FLAGS += -D__Linux__
    else
         CURRENT_OS += Windows
         OS_FLAGS += -D__Windows__
    endif

or something equivalent, and after that, use ifdef / endif  to define everything, and at the end, use only one generic rule.

HTH

**Comment by AugustoRuiz** [comment]
Have a look at the Makefile now ;)

**Comment by ebachard** [comment]
Wow, "  make " now works perfectly on Linux. If this can help,  "make clean"  and "make cleanall" work as expected too.

I think you fixed the issue elegantly !

**Comment by AugustoRuiz** [comment]
Thank you! :)
